# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtCore import Qt

import process_image
import cv2

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setGeometry(QtCore.QRect(400, 610, 280, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_reset.setFont(font)
        self.button_reset.setObjectName("button_reset")
        self.button_reset.setStyleSheet("""
                                        QPushButton{ 
                                            background-color: rgb(0,150,255);
                                            border-radius: 20px; 
                                            border: 5px solid; 
                                            border-color: rgb(0,150,255);}
                                        QPushButton:hover{
                                            border-color: rgb(255,0,255)}
                                        QPushButton:pressed{
                                        background-color: rgb(255,0,255)}""")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1081, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.img_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_2.sizePolicy().hasHeightForWidth())
        self.img_2.setSizePolicy(sizePolicy)
        self.img_2.setText("Image 2")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.img_2.setFont(font)
        self.img_2.setScaledContents(True)
        self.img_2.setAlignment(Qt.AlignCenter)
        self.img_2.setObjectName("img_2")
        self.gridLayout.addWidget(self.img_2, 1, 0, 1, 1)
        self.diff_image = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diff_image.sizePolicy().hasHeightForWidth())
        self.diff_image.setSizePolicy(sizePolicy)
        self.diff_image.setText("Result 2")
        self.diff_image.setFont(font)
        self.diff_image.setScaledContents(True)
        self.diff_image.setAlignment(Qt.AlignCenter)
        self.diff_image.setObjectName("diff_image")
        self.gridLayout.addWidget(self.diff_image, 1, 1, 1, 1)
        self.absdiff_image = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absdiff_image.sizePolicy().hasHeightForWidth())
        self.absdiff_image.setSizePolicy(sizePolicy)
        self.absdiff_image.setText("Result 1")
        self.absdiff_image.setFont(font)
        self.absdiff_image.setScaledContents(True)
        self.absdiff_image.setAlignment(Qt.AlignCenter)
        self.absdiff_image.setObjectName("absdiff_image")
        self.gridLayout.addWidget(self.absdiff_image, 0, 1, 1, 1)
        self.img_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_1.sizePolicy().hasHeightForWidth())
        self.img_1.setSizePolicy(sizePolicy)
        self.img_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_1.setText("Image 1")
        self.img_1.setFont(font)
        self.img_1.setScaledContents(True)
        self.img_1.setAlignment(Qt.AlignCenter)
        self.img_1.setObjectName("img_1")
        self.gridLayout.addWidget(self.img_1, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 530, 1081, 61))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_Th1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Th1.sizePolicy().hasHeightForWidth())
        self.button_Th1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_Th1.setFont(font)
        self.button_Th1.setObjectName("button_Th1")
        self.button_Th1.setStyleSheet("""
                                    QPushButton{ 
                                        background-color: rgb(0,150,255);
                                        border-radius: 20px; 
                                        border: 5px solid; 
                                        border-color: rgb(0,150,255);}
                                    QPushButton:hover{
                                        border-color: rgb(255,0,255)}
                                    QPushButton:pressed{
                                    background-color: rgb(255,0,255)}""")
        self.horizontalLayout.addWidget(self.button_Th1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_Th2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Th2.sizePolicy().hasHeightForWidth())
        self.button_Th2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_Th2.setFont(font)
        self.button_Th2.setObjectName("button_Th2")
        self.button_Th2.setStyleSheet("""
                                        QPushButton{ 
                                            background-color: rgb(0,150,255);
                                            border-radius: 20px; 
                                            border: 5px solid; 
                                            border-color: rgb(0,150,255);}
                                        QPushButton:hover{
                                            border-color: rgb(255,0,255)}
                                        QPushButton:pressed{
                                        background-color: rgb(255,0,255)}""")
        self.horizontalLayout.addWidget(self.button_Th2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        self.menuAdd_Image = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Image.setObjectName("menuAdd_Image")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImage_1 = QtWidgets.QAction(MainWindow)
        self.actionImage_1.setObjectName("actionImage_1")
        self.actionImage_2 = QtWidgets.QAction(MainWindow)
        self.actionImage_2.setObjectName("actionImage_2")
        self.menuAdd_Image.addAction(self.actionImage_1)
        self.menuAdd_Image.addAction(self.actionImage_2)
        self.menubar.addAction(self.menuAdd_Image.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_reset.setText(_translate("MainWindow", "RESET"))
        self.button_Th1.setText(_translate("MainWindow", "TH1"))
        self.button_Th2.setText(_translate("MainWindow", "TH2"))
        self.menuAdd_Image.setTitle(_translate("MainWindow", "Add Image"))
        self.actionImage_1.setText(_translate("MainWindow", "Image 1"))
        self.actionImage_2.setText(_translate("MainWindow", "Image 2"))

        self.actionImage_1.triggered.connect(lambda: self.add_image(1))
        self.actionImage_2.triggered.connect(lambda: self.add_image(2))

        self.button_Th1.clicked.connect(self.button_1)
        self.button_Th2.clicked.connect(self.button_2)
        self.button_reset.clicked.connect(self.reset_image)

    def add_image(self, image):
        global lis_img
        file_name = QFileDialog.getOpenFileName()
        image_path = file_name[0]
        if image_path.endswith('jpg') or image_path.endswith('png'):
            lis_img.append(image_path)
            if len(lis_img) > 2:
                lis_img.clear()
                lis_img.append(image_path)
            self.show_image(image_path, image)

    def show_image(self, path, image):
        if image == 1:
            self.img_1.setPixmap(QtGui.QPixmap(path))
        elif image == 2:
            self.img_2.setPixmap(QtGui.QPixmap(path))

    def button_1(self):
        global lis_img
        if len(lis_img) == 2:
            img = process_image.process_Th1(lis_img)
            self.absdiff_image.setPixmap(self.convert_cv_qt(img))

    def button_2(self):
        global lis_img
        if len(lis_img) == 2:
            img = process_image.process_Th2(lis_img)
            self.diff_image.setPixmap(self.convert_cv_qt(img))

    def convert_cv_qt(self, cv_img):
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        # p = convert_to_Qt_format.scaled(self.disply_width, self.display_height, Qt.KeepAspectRatio)
        return QtGui.QPixmap.fromImage(convert_to_Qt_format)

    def reset_image(self):
        global lis_img
        lis_img.clear()
        self.img_1.setText("Image 1")
        self.img_2.setText("Image 2")
        self.absdiff_image.setText("Result 1")
        self.diff_image.setText("Result 2")

lis_img = []

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
